import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "../Components/LayoutWrapper.jsx";
import AuthProvider from "@/Provider/AuthProvider";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "../Components/theme-provider.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
              <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
         <LayoutWrapper>{children}</LayoutWrapper>
          <Toaster position="top-right" reverseOrder={false} />

          </ThemeProvider>
 
        </AuthProvider>
      </body>
    </html>
  );
}
